GET http://localhost:3000/players/

###
POST http://localhost:3000/players/
Content-Type: application/json

{
  "playerName": "Vishal",
  "jerseyNumber": 17,
  "role": "Bowler"
}

# {
#   "playerName": "kapil",
#   "jerseyNumber": 15,
#   "role": "Bowler"
# }

###
// get player detail
GET http://localhost:3000/players/4/

###
//Updates the detail

PUT  http://localhost:3000/players/1/
Content-Type: application/json

{
  "playerName": "Maneesh",
  "jerseyNumber": 54,
  "role": "All-rounder"
}

###
//  Deletes a player

DELETE http://localhost:3000/players/2/


